languageCode = "en-us"
title = "lw's blog"
author = "lw"
contentdir = "content"
publishdir = "public"
theme = "slim"
disqusShortname = "lw2904"
baseURL = "https://lw2904.github.io"

[params]
  Subtitle = ""
  GithubID = "lw2904"
  DisqusShortname = ""
  Summary = true  # takes true or false
  Content = false  # takes true or false
  # if both are set to true, summary is shown.
  FooterMsg = " "