languageCode = "en-us"
title = "lw's blog"
author = "lw"
contentdir = "content"
publishdir = "public"
theme = "pixyll"
disqusShortname = "lw2904"
baseURL = "https://lw2904.github.io/"

[params]
  navigation = ["archives.md", "about.md"]
